namespace AiPrReviewer.Services.AI;

public class AiCommentFormatter
{
    public string FormatComment(string aiFeedback)
    {
        return $""" 
        🧠 **Automated Review Summary**

        {aiFeedback}

        ---
        _This review was generated by AiPrReviewer, a tool that uses AI to review pull requests._
        """;
    }
}