namespace AiPrReviewer.Application.AI;

public class AiCommentFormatter
{
    public string FormatComment(string aiFeedback)
    {
        string comment = $""" 
        🧠 **Automated Review Summary**

        {aiFeedback}

        ---
        _This review was generated by AiPrReviewer, a tool that uses AI to review pull requests._
        """;

        return comment;
    }
}