using System.Collections.Generic;
using System.Linq;

namespace AiPrReviewer.Application.AI;

public class AiCommentFormatter
{
    public string FormatComment(string aiFeedback, IEnumerable<string>? ruleWarnings = null)
    {
        var warnings = ruleWarnings?.ToList() ?? new List<string>();
        
        string comment = $""" 
        🧠 **Automated Review Summary**

        {aiFeedback}
        """;

        if (warnings.Any())
        {
            comment += "\n\n⚠️ **Rule Warnings:**\n";
            foreach (var warning in warnings)
            {
                comment += $"- {warning}\n";
            }
        }

        comment += "\n---\n_This review was generated by AiPrReviewer, a tool that uses AI to review pull requests._";

        return comment;
    }
}